spring:
    application:
        name: schema-registry-demo-service

kafka:
    bootstrap-servers: localhost:9092
    schema.registry.url: http://localhost:8081

server:
    port: 9001

kafkademo:
    inboundTopic: "send-payment"
    outboundTopic: "payment-sent"
